[[local|localrc]]
ADMIN_PASSWORD=root
DATABASE_PASSWORD=$ADMIN_PASSWORD
RABBIT_PASSWORD=$ADMIN_PASSWORD
SERVICE_PASSWORD=$ADMIN_PASSWORD

DEST=/opt/stack

enable_plugin performance-weighted-scheduler https://github.com/edoardocarpentiero/PerformanceWeightedScheduler.git main

HOST_IP=10.0.2.15

enable_service g-api g-reg
enable_service c-api c-vol c-sch 

CINDER_ENABLED_BACKENDS=low_cap,mid_cap,high_cap
CINDER_VOLUME_TYPES=general_storage,low_cap,mid_cap,high_cap


[[post-config|$CINDER_CONF]]
[DEFAULT]
default_volume_type = general_storage

[low_cap]
volume_group=vg-low
volume_driver=cinder.volume.drivers.lvm.LVMVolumeDriver
volume_backend_name=LVM_BACKEND_1
lvm_type = default
max_over_subscription_ratio = 1.0
storage_type_plugin=HDD
description=Backend capacità 5GB


[mid_cap]
volume_group=vg-mid
volume_driver=cinder.volume.drivers.lvm.LVMVolumeDriver
volume_backend_name=LVM_BACKEND_2
lvm_type = default
max_over_subscription_ratio = 1.0
storage_type_plugin=SSD
description=Backend capacità 20GB


[high_cap]
volume_group=vg-high
volume_driver=cinder.volume.drivers.lvm.LVMVolumeDriver
volume_backend_name=LVM_BACKEND_3
lvm_type = default
max_over_subscription_ratio = 1.0
storage_type_plugin=HDD
description=Backend capacità 100GB

[general_storage]
description=Volume type generico. Lo scheduler deciderà quale BE usare







